### ISSUE TITLE
关于地图

### ISSUE THREAD

**Issue by yelloxing** [ClayFoundation/Sunflower#1]
@woaidouya123 
地图绘制的时候好像有点问题：
1.进入一个区域以后，提示文字就不跟鼠标走了；
2.鼠标试图移动到提示文字上时候，抖动严重。

或许你可以参考一下区域的用法：
https://github.com/ClayFoundation/examples/blob/master/use-case/barPolar.html

**Comment by woaidouya123** [comment]
已解决，请更新代码
